name: Cross Compile C File

on:
  push:
    branches:
      - Main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Cross-Compiler (e.g., for ARM)
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf

    - name: Build helloWorld.c
      run: |
        arm-linux-gnueabihf-gcc helloWorld.c -o helloWorld.exe

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: helloWorld.exe
        path: helloWorld.exe
